### ISSUE TITLE
work without the tick

### ISSUE THREAD

**Issue by fahad9022** [lguipeng/AnimCheckBox#8]
when i press the checkbox it works nicely,
but when i use 
`setchecked=true;`
it looks like this 
![screenshot 2f e2 80 8f 2f - -](https://cloud.githubusercontent.com/assets/10420072/22077308/ae8d0aa2-ddc4-11e6-87c4-9160c7d9bae6.png)

**Comment by lguipeng** [comment]
It doesn't make any sense,  because I also use setChecked method when the button is clicked.

**Comment by fahad9022** [comment]
and why that happened ?

**Comment by lguipeng** [comment]
use setChecked(checked, false) instead !

**Comment by anitaa1990** [comment]
Not working. Still facing the same issue. Works without the tick only.
