### ISSUE TITLE
how to disable checkbox in xml?

### ISSUE THREAD

**Issue by khalid-mahmood** [lguipeng/AnimCheckBox#9]
i want checkbox checked and disabled ? how can

**Comment by lguipeng** [comment]
try setEnabled(false)

**Comment by khalid-mahmood** [comment]
@lguipeng i want to  disable initially in xml.
don't want do something is code.

**Comment by lguipeng** [comment]
@khalid-mahmood I also try click = "false" in xml, but it is invalid， because I call setOnClickListener on init method. So the conclusion is you can just only use setClickable(false) or setEnable(false) in code to fix this.

**Comment by khalid-mahmood** [comment]
@lguipeng its nice widget i was about to use it.. but that's the problem. hope so you will fix it in future. 
Nice work although.

**Comment by lguipeng** [comment]
@khalid-mahmood You can copy AnimCheckBox.java to your project, and it is easy to fix this with only few code.

**Comment by khalid-mahmood** [comment]
@lguipeng thanks. i would try it.
